module.exports = select

function select (theme = 'darkTheme') {
  return themes[theme]
}

// define colors
const bluePurple = '#6700ff'
const lightGreen = '#09FFC3'
const lightGreenHover = '#A1FFE8'
const greyEB = '#EBEBEB'
const grey8D = '#8D8D8D'
const grey31 = '#313136'
const grey33 = '#333333'
const greyBB = '#BBBBBB'
const white = '#ffffff'
const dark18 = '#181920'
const dark1d = '#1d1d26'
const peach = 'rgba(255, 41,117, 100)'
const transparent = 'rgba(0,0,0,0)'

// define font
const fontNunito = `'Nunito', sans-serif`
const fontInconsolata = `'Inconsolata', monospace`

const lightTheme = {
  '--main-font': fontNunito,
  '--code-font': fontInconsolata,
  '--h1': '6rem',
  '--h2': '5rem',
  '--h3': '4rem',
  '--h4': '3rem',
  '--h5': '2rem',
  '--h6': '1.6rem',
  '--body-color': grey33,
  '--body-background': greyEB,
  '--wrapper-padding': '0 30px',
  '--button-default': lightGreen,
  '--button-default-hover': white,
  '--button-default-font-size': '1.8rem',
  '--button-default-text': dark1d,
  '--button-default-text-hover': dark1d,
  '--button-default-radius': '22px',
  '--button-default-padding': '10px 30px',
  '--button-padding-right': '30px',
  '--button-padding-left': '30px',
  '--button-border': '0px solid var(--button-white)',
  '--button-box-shadow': 'none',
  '--editor-preview': white,
  '--card-cover': greyEB,
  '--card-hover-cover': lightGreen,
  '--card-cover-border': transparent,
  '--card-border': transparent,
  '--card-hover-border': '0px solid var(--card-border)',
  '--card-code-overlay': 'linear-gradient(0deg, rgba(0,0,0, .1) 0%, rgba(0,0,0, .28) 100%)',
  '--card-shadow': '0px 6px 8px rgba(144, 144, 144, .3)',
  '--card-hover-shadow': '0px 6px 8px rgba(144, 144, 144, .3)',
  '--card-code-text': '1.3rem',
  '--card-code-text-line-height': '20px',
  '--card-code-width': 'calc(100% - 40px)',
  '--card-code-height': 'calc(100% - 30px)',
  '--card-code-padding': '15px 20px',
  '--card-cover-title': grey31,
  '--card-hover-cover-title': grey31,
  '--card-cover-userInfo': grey33,
  '--card-time': grey8D,
  '--card-hover-time': grey8D,
  '--card-visit-icons-fill': dark1d,
  '--search-input': `1px solid var(--search-input-border)`,
  '--search-input-border': 'rgba(255,255,255, 0)',
  '--search-input-background': white,
  '--search-input-color': grey8D,
  '--search-input-text': '1.4rem',
  '--search-icon-fill': dark1d,
  '--search-button-color': dark1d,
  '--search-button-background': white,
  '--search-button-hover-background': lightGreen,
  '--text-large': '2rem',
  '--text-normal': '1.6rem',
  '--text-small': '1.4rem',
  '--text-xsmall': '1.2rem',
  '--pages-current-background': white,
  '--pages-border': '0px solid rgba(0,0,0,0)',
  '--pages-text': grey8D,
  '--pages-text-active': dark1d,
  '--pages-text-border-radius': '4px',
  '--pages-hover-background': white,
  '--grid-template': '',
  '--icon-new-fill': dark1d,
  '--pagination-button-icon-fill': dark1d,
  '--collectionArea-grid-gap': '30px',
  '--collectionCard-border-radius': '6px',
  '--pages-li-color': grey8D,
  '--search-button-border-radius': '30px',
}

const darkTheme = {
  '--main-font': fontNunito,
  '--code-font': fontInconsolata,
  '--h1': '6rem',
  '--h2': '5rem',
  '--h3': '4rem',
  '--h4': '3rem',
  '--h5': '2rem',
  '--h6': '1.6rem',
  '--body-color': white,
  '--body-background': dark18,
  '--wrapper-padding': '0 30px',
  '--button-default': transparent,
  '--button-default-hover': bluePurple,
  '--button-default-font-size': '1.8rem',
  '--button-default-text': peach,
  '--button-default-text-hover': peach,
  '--button-default-radius': '22px',
  '--button-default-padding': '10px 30px',
  '--button-padding-right': '30px',
  '--button-padding-left': '30px',
  '--button-border': '1px solid #6700ff',
  '--button-box-shadow': '0 1px 8px rgba(255,41,117, .3)',
  '--editor-preview': dark1d,
  '--card-cover': grey31,
  '--card-hover-cover': bluePurple,
  '--card-cover-border': transparent,
  '--card-border': bluePurple,
  '--card-hover-border': '1px solid var(--card-border)',
  '--card-code-overlay': 'linear-gradient(0deg, rgba(103,0,255, .1) 0%, rgba(103,0,255, .28) 100%)',
  '--card-shadow': '0px 2px 30px rgba(103, 0, 255, 0)',
  '--card-hover-shadow': '0px 2px 30px rgba(103, 0, 255, .6)',
  '--card-code-text': '1.3rem',
  '--card-code-text-line-height': '20px',
  '--card-code-width': 'calc(100% - 40px)',
  '--card-code-height': 'calc(100% - 30px)',
  '--card-code-padding': '15px 20px',
  '--card-cover-title': lightGreen,
  '--card-hover-cover-title': white,
  '--card-cover-userInfo': white,
  '--card-time': greyBB,
  '--card-hover-time': white,
  '--card-visit-icons-fill': white,
  '--search-input': `1px solid var(--search-input-border)`,
  '--search-input-border': bluePurple,
  '--search-input-background': 'none',
  '--search-input-color': lightGreen,
  '--search-input-text': '1.4rem',
  '--search-icon-fill': lightGreen,
  '--search-button-color': white,
  '--search-button-background': white,
  '--search-button-hover-background': bluePurple,
  '--text-large': '2rem',
  '--text-normal': '1.6rem',
  '--text-small': '1.4rem',
  '--text-xsmall': '1.2rem',
  '--pages-current-background': transparent,
  '--pages-border': '1px solid #6700ff',
  '--pages-text': peach,
  '--pages-text-active': white,
  '--pages-text-border-radius': '4px',
  '--pages-hover-background': bluePurple,
  '--grid-template': '',
  '--icon-new-fill': white,
  '--pagination-button-icon-fill': peach,
  '--collectionArea-grid-gap': '30px',
  '--collectionCard-border-radius': '6px',
  '--search-button-border-radius': '30px',
}
const themes = { lightTheme, darkTheme }
select.names = Object.keys(themes)
